In [2]:
# numpy
import numpy as np 


In [16]:
a=np.array([1,2,3,4],dtype=np.float64)
b=np.array([3,4,5,6],dtype=np.float64)

In [17]:
np.stack([a,b],axis=1) 

array([[1., 3.],
       [2., 4.],
       [3., 5.],
       [4., 6.]])

In [23]:
print(type(a))
print(a.reshape(2,2))


<class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]]


In [32]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
np.ones((3,4)), np.zeros((3,4))

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [38]:
np.eye(3)*20

array([[20.,  0.,  0.],
       [ 0., 20.,  0.],
       [ 0.,  0., 20.]])

In [44]:
# perform all matematical operations 
a=np.array([2,3,4,5,6],dtype=np.float16)
b=np.arange(0,5).reshape(5,1)
a*b


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 4.,  6.,  8., 10., 12.],
       [ 6.,  9., 12., 15., 18.],
       [ 8., 12., 16., 20., 24.]])